### ISSUE TITLE
Creation idea: Sitting Human Detector

### ISSUE THREAD

**Issue by forno** [CIRKIT-ARC-1stGrade/opencv3mixing#10]
Hi @CIRKIT-ARC-1stGrade/opencv3-developers 

We have challenge tasks for tsukuba challenge.
Here, We need detector for sitting human.
http://www.tsukubachallenge.jp/tc2017/kadai

Could you make it together?

**Comment by Kose-i** [comment]
I have few times, but try to do it.

**Comment by yasu80** [comment]
First of All, Roadmaps.

# RoadMaps

## 1. Color Detection

Simple Color Detection on the Develop Enviromnent & Publish the point status.

## 2. Shape Detection

Simple Shape Detection on the Develop Enviromnent & Publish the point status.

## 3. Mixed Feature Detection

Detect Shape, Color and Feature of  the Target.

※Human Feature can be hard to explain, and we may use Clasiifier or DeepLearning....
but even in this case, we can use the skills above to detect Feature values.

## 4. Optimise

System should be as fast as poosible it can be. and moving environment make it hard to detect targets.

I will back soon, at least in few days , and gonna join it. Then Lets make specs of each.
あとなんで英語なんですかね( I don't understand the reason why we tak are taking the trouble to use English )

**Comment by forno** [comment]
@yasu80
特に意味はないです(toku ni imi ha nai desu

**Comment by yasu80** [comment]
まずロードマップが要りますね.

# ロードマップ

## 1. 色検出


開発環境における簡単な色検出を行い, 検出したターゲットのポイント(重心点)をパブリッシュします.
または, 二値化した画像をパブリッシュします.

## 2. 形状検出

開発環境における簡単な形状検出を行い, 検出したターゲットのポイント(重心点)をパブリッシュします.
または, ボーンの代表点としてパブリッシュします.

## 3. 要素を統合しての検出

開発環境において複合要素による, 複合要素を持つ一般物体を検出します.

※人間の形状は決め打ちのハードコーディングにするには複雑すぎると思われますので, 分類器(分類データ)を借りててくるか強化学習を用いた手法を用いることになるかもしれません
しかしこのような場合でも, 上記の手法を用いることは可能です.

## 4. 最適化
システムは実行環境(本番環境)において最適な速度を保つことが要求されます.

**Comment by dorayaki0903yamamoto** [comment]
# 参加します

**Comment by forno** [comment]
CIR-KITはKinectを保有しており，
画像のみの処理に止まらず，
距離情報を利用することもできます．

普通にカメラを乗せて検出するのもありです．

よければ２６日とかにでも
集まってお話ししません？

**Comment by yasu80** [comment]
それがいいと思います. なるだけ多く参加して欲しいところですが..

**Comment by forno** [comment]
Hi @CIRKIT-ARC-1stGrade/opencv3-developers 

ひとまず画像を受け取る方法を整備しますね。
グローバルへの依存はポイしたランチファイルの生成をしておきます。

その間に #12 の対応を @CIRKIT-ARC-1stGrade/1st-grades の人がやるのです・・・のです・・・。

**Comment by forno** [comment]
画像表示のlaunchファイル追加しました。 by #11 

あとはこれでデバッグしながら作ってくだけかなー

**Comment by yasu80** [comment]
大体話がまとまったみたいなのでcloseしたいと思います
