### ISSUE TITLE
Test on Acculacy of Color Detection(色検出の精度試験)

### ISSUE THREAD

**Issue by yasu80** [CIRKIT-ARC-1stGrade/opencv3mixing#12]
Now We have Logicool C270 WebCam for UVC

![image](https://user-images.githubusercontent.com/16016288/29610472-37b62604-8835-11e7-8f93-e72469d7c43e.png)

How is the accuracy of the Detection? We need to know NOW, if any, within  2 ~ 3 days.

...Considered all, except UVC cam (such as Analog Cams) are useless even though it has clear sight, for they need converter...

ロジクールC270において色検出の制度を検討してください.  メソッドは不問. 7 ~ 10 m において A4用紙サイズの色紙的なものをターゲットとして良好な結果が出ればそれでいいです. できれば2 ~ 3 作業日で.

**Comment by forno** [comment]
Remind!

**Comment by marubashi11** [comment]
検出にinRange関数を用い、閾値はcolor_detectブランチのcolor_detect.cppにあげているもので試したところ、オレンジ色の検出はせいぜい3m離れたところからが限界のようでした。それ以上離れるとノイズと混じってわからなくなったり検出がチラついたりします。
カメラの精度のせいなのかもしれませんが、閾値をさらに絞ることでも改善するかもしれないのでちょっと試してみます。

**Comment by tanacchi** [comment]
@marubashi11 君 を筆頭に、一年生たちがよく調べて頑張ってくれました。
ありがとうございました。
ということで、閉じー

**Comment by forno** [comment]
お疲れ様でしたー．
