### ISSUE TITLE
We need package.xml and CMakeList.txt for ROS system

### ISSUE THREAD

**Issue by forno** [CIRKIT-ARC-1stGrade/opencv3mixing#2]
We need the ROS package.

But here haven't  package.xml and CMakeLists.txt.
We can create this files by handy.

Please create them.

## Note
Please many commits as soon as possible.
That is your working path.
Challenge it and share work path to optimize it. 

Don't forget to checkout branch.

**Comment by Kose-i** [comment]
ok!

**Comment by forno** [comment]
Fixed!
