### ISSUE TITLE
Human detection on machine learning (機械学習による人物検出)

### ISSUE THREAD

**Issue by tanacchi** [CIRKIT-ARC-1stGrade/opencv3mixing#22]
本走行まで１ヶ月を切ってしまい、時間が許してくれるかは定かではありませんが、実現性としてはかなり期待できるものがあります。
ご検討ください。

ここでは厳密なメカニズムには触れずに、作業の流れだけ説明します。

## 作業内容

1. 学習するための画像データを用意する
   画像データをとにかく集めなければなりません。
   具体的には
   * **正解画像**（検出対象が含まれる画像）
   * **不正解画像**（検出対象が含まれない画像）

   を用意する必要があります。
   また正解画像に関しては以下のことに留意する必要があります。

   * **場所**（背景）を何回か変えること
   * 被写体となる**人物**を何回か変えること
   * 万一のため、**雨天での撮影**も行うこと

   不正解画像については特に指定はありませんが、ダミー画像（服装を変えるなど）を使用をするとより高い精度を期待できます。
   また、ある程度の精度を出すには**正解画像：７０００枚、不正解画像：３０００枚**を用意する必要があります。
2. ラベル付け
   学習させる上で、各画像において**検出対象が存在するのか**、あるのなら**どこにあるのか**を先に登録しておく必要があります。
   検出対象の位置は座標で指定してやる必要があります。非常に手間の掛かりそうな作業ですが、**ここに関しては手作業です。**
   しかし、範囲選択するだけで座標を指定できて、しかも分類器生成に適した形式で保存してくれる
   **神**みたいなツールが存在しますので後ほど紹介します。

3.  分類器の生成
   ~~上の作業で５〜６時間ぶっ続けで働いて果てそうになったところで~~次に分類器の生成に移ります。2の工程がうまくいってたら、

   info.dat
   ___
   static/img/1004.jpg  1  334 58 485 567
   static/img/1005.jpg  1  235 173 657 574
   static/img/1006.jpg  2  318 38 103 128  179 49 136 152
   static/img/1008.jpg  1  270 81 271 365
   static/img/1009.jpg  1  816 41 212 235
  ___     
   bg.txt
  ___
   static/img/10004.jpg
   static/img/10005.jpg
   static/img/10007.jpg
   static/img/10008.jpg
   static/img/10009.jpg
   ___
   ↑のように正解画像と検出対象の位置のリスト（info.dat）と、不正解画像のリスト（bg.txt）ができていると思います。ここから分類器を .xml形式で生成していくという感じになります。此処から先は下のサイトで確認してください。
   [一番参考になったサイト](http://shkh.hatenablog.com/entry/2012/11/03/052251 "OpenCV 2.4.2で分類器を作る")

## ラベル付けに使えるツールの紹介
   [TrainingAssistant](https://github.com/shkh/TrainingAssistant)
   shkhさんという筑波のお方が個人的に作られたみたいです。 手元端末で動作確認済みです。
   README.mdを見ればだいたい使い方はわかりますが、検出対象を範囲指定したあと、
   枠外をクリックして**赤枠になったことを確認して**NEXTに進むよう注意してください。そうしないと不正解画像として登録されてしまうみたいです。
 ___
そういえば人物探索したあとの挙動についても考えなきゃだけど
そのへんは５号機リポジトリissueで、ということで

**Comment by tanacchi** [comment]
かかる時間の目安としては
1. 素材集め：２時間〜２日
2. ラベル付け：（１００００枚を一人で仕分けした場合）１０時間
3. 分類器生成：以下の条件で丸２日
    * 対象画像
    * Core 2 duo (3.06GHz)
    * メモリ 16GB
    * プロセスの優先度 -20

とりかかるなら早いに越したことないです。

**Comment by tanacchi** [comment]
cascade.xml の生成まで成功しました。よく出来てますわ流石つくｂ（ｒｙ

**Comment by tanacchi** [comment]
試してみて気づいたことメモ
* スマホで撮るときは、撮影者側から見てカメラが右に来るように、横向きにする(縦長だとccwに90度回転しちゃう)
* とった写真を一旦GoogleDriveにアップして、PCに移す
* アップするときは40枚ずつを目安に（一気にするとアプリが昇天する）
* 拡張子が.JPGだと読み込めないが、.jpgに名前を変えるだけでちゃんと動く
* 枠の外を一回クリックすることを徹底すること（よく忘れる）
* ５枚め過ぎたあたりから鬼のように重たい
* ４００枚撮って、Drive にアップするだけでスマホの充電が３０％くらいなくなる
* 分担してやろうにも画像名がかぶると死しか見えない->ユニークな名前に変更するシェルスクリプトを書いたので解決した。
* 学習に4日かかる計算で犠牲になってくれるPCちゃんがいる

**Comment by tanacchi** [comment]
![screenshot from 2017-10-09 19-27-32](https://user-images.githubusercontent.com/19949534/31334235-64e16ce8-ad28-11e7-9b14-9e7b2436093b.png)
正解画像１８９枚、不正解画像６枚で作ったsascade分類器で
ティッシュ箱（scottie）を検出するテストをしてみました。
~~ガバガバ過ぎて草生えるんじゃぁ＾〜~~
学習材料が鬼のように少なく、学習時間も丸１日かかる予定がものの３０秒で終わってしまったので結果はお察しでした。
しかし時間をかければ人物探索もいけるのでは？

**Comment by tanacchi** [comment]
ちなみに今回かかった時間は3~4時間です

**Comment by tanacchi** [comment]
https://drive.google.com/open?id=0B3Lz4dIcgscxeUxPSHJIODdMLVk
CIR-KIT のGoogleDriveに画像をストックするのが厳しそうだったので、私のGoogleDrive内のフォルダを共有する形でいきたいと思います。
**PositiveImages**フォルダに**正解画像**を、**NegativeImages**に**不正解画像**を保存していってください。
スマホアプリの方のGoogleDriveから保存するとスムーズです。

**Comment by tanacchi** [comment]
↑人物探索用のデータということで、緑のズボンを被って（？）オレンジのゼッケン着て帽子もかぶった状態で、かつ屋外で撮影します

**Comment by yasu80** [comment]
GPUつきのPCで遊んでるやつがいるんですが要ります？
某所(私の勤め先)で走らせることができます

**Comment by tanacchi** [comment]
その方が差し支え無ければ、是非お願いしたいです

**Comment by forno** [comment]
機械学習で画像検出するなら、
なんの検出器ができたのかのチェックを初めにするといいですよ。

トレーニングデータで検出評価するのはご法度ですが、
なんの検出器になったのか確認するには有用です。

もし、トレーニングデータで検出できないなら
（データ数が足りないという根本的な問題を除けば）
目標のもの以外の検出器になっている場合があります。

乱数を変えて再度生成してみたら、うまくいく場合もあるので
特にNNを利用している場合は何個もモデル生成してみてください。
（データ数が足りないという根本的な問題を除けば）

**Comment by yasu80** [comment]
@marubashi11 
えーっと, NegativeImageのほうに正解画像入ってませんか?

**Comment by tanacchi** [comment]
@forno レスポンスありがとうございます
参考にさせていただきます

**Comment by yasu80** [comment]
@tanacchi 
わかりました. 
 - https://drive.google.com/open?id=0B3Lz4dIcgscxeUxPSHJIODdMLVk にPositiveImagesディレクトリ追加しておきました
   - 溜まったらやります
@forno
触ってないですが
 - 範囲選択ツールについてソレ本当にうまく行ってるのって気はします. 検証します

**Comment by tanacchi** [comment]
@yasu80 レスポンスありがとうございます。info.dat も bg.txt も内容含め正常に生成されてたのでおそらく問題ないと思われます

**Comment by tanacchi** [comment]
画像サイズをカメラからのデータに合わせてリサイズしてみたんですがどうでしょう。
![100154](https://user-images.githubusercontent.com/19949534/31384856-bc5b28a0-adfb-11e7-9be6-7f739ae83ebd.jpg)
HAAR-LIKE特徴分類器は明暗差を元に特徴量を出すから致命的ではないかもしれませんが
この画質は流石にまずいですかね。。。
一応パラメータをいろいろいじってみたのですが、だいたいこんな感じになります。

**Comment by tanacchi** [comment]
ぼかしフィルターなんかも試してみますん

**Comment by tanacchi** [comment]
ちょっとぼかしを入れてみました。
![100001](https://user-images.githubusercontent.com/19949534/31391101-928ec1f2-ae10-11e7-86f9-d7f35a9518ba.jpg)
つぶつぶが目立たなくなってかつ境界もはっきりしているのでこのくらいが妥当かなと思います。
リサイズしてぼかしをかけるだけで容量が１００分の１くらいになりました。

**Comment by tanacchi** [comment]
１００分の１は嘘です。１０分の１です。

**Comment by tanacchi** [comment]
HaarLike特徴分類器は白黒画像をもとに識別するので、オレンジ色検出と併用するとより確実と思われる。

**Comment by yasu80** [comment]
すみません, 使っているツールについてちょっと誤解していました

## Haar-Cascade Classifier の挙動について
この分類器は特定の形状(故に白黒)の特徴量を割り出すことで入力画像について分類器に当てはまる形状があるかどうかを割り出します. 故に, 対象物体のポジションは一定でなくてはならないので, 撮影者のアングルをある程度制限する必要があります.

で, どうするかというと 正面付近のみの検出器, 横向きの, 後ろ向きのっていう具合に一個づつ作っていく必要があるような気がします

**Comment by tanacchi** [comment]
時間が（天気が）許してくれなかったということで計画中断とします。
今回は西田研究室のデータを使わせていただくことになりましたが、精度次第では来年に再始動させるつもりです。今まで取ってきたデータは保持しておきます。
See you ~~.

**Comment by yasu80** [comment]
#25

**Comment by yasu80** [comment]
No Nishida Data available dude...
Then Reopen From Workstation (NO JP sry)

**Comment by yasu80** [comment]
Need Image on GoogleDrive plz

**Comment by tanacchi** [comment]
導入は当分見送りです
閉じます
