### ISSUE TITLE
機械学習に向けての仕事内容

### ISSUE THREAD

**Issue by tanacchi** [CIRKIT-ARC-1stGrade/opencv3mixing#23]
#22 の方に書いたとは思いますが改めてうｐし直します。質問等ありましたらここで受け付けます。
**気づいたことがあり次第更新するので、参加してくれる方はよく見ておいてください。**

**Comment by tanacchi** [comment]
# 第一段階　画像集め
### 要求
  * 正解画像：７０００枚、不正解画像：３０００枚
  * 10/15（日）までには揃うように

### 撮影の際の注意事項
  * スマホで撮るときは、撮影者側から見てカメラが右に来るように、横向きにすること
  * 場所（背景）を何回か変えること
  * 被写体となる人物を何回か変えること
  * 出来ることなら、雨天時の撮影も行うこと
  * なるべく本番の環境に沿った状態を作ること　<-- new !
     - つくばの現場画像を参考に
     - 被写体は正面を向いたまま動かない
     - ９時〜１５時の間に撮影を行うこと
     - 横の看板も用意する　など
  * 撮影する高さは実際のカメラの位置に合わせること   <-- new !
### **正面からの写真、側面からの写真とを分けて保存すること（フォルダ）**

### 動画をアップロードする方法
  * 携帯端末にGoogleDrive　をインストールしておく
  * https://drive.google.com/open?id=0B3Lz4dIcgscxeUxPSHJIODdMLVk のフォルダに画像を保存する。
  * 正解画像は PositiveImages に、不正解画像は NagetiveImages に保存する
  * 保存するときは４０枚ずつを目安に

**Comment by yasu80** [comment]
AndroidだとSD差してPCから20分くらいで直上げできました
948枚くらい一気に行けました

**Comment by yasu80** [comment]
気がついたんですけれど, 先日の写真含めて看板用意してないですね

すみません, 公式確認しましたらこんな感じだそうです
![image](https://user-images.githubusercontent.com/16016288/31423020-da4c2bfc-ae8c-11e7-806c-14efeebeee60.png)
****

**Comment by tanacchi** [comment]
正面画像と側面画像を一挙に学習データとして扱うのはどうなのか・・？

**Comment by tanacchi** [comment]
## 正面からの画像と、側面からの画像を分けて保存すること
FrontフォルダとSideフォルダに分けての保存をおねがいします。
撮りに行く時に「正面から撮る係」なんかを決めればいいと思います。
正面からの角度が６０度以上行くようならSideフォルダへ。
そう厳密に考える必要は無いです
枚数的には同じくらいほしい

**Comment by tanacchi** [comment]
#22 と同じく
